/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package savethesystem.ui;
import savethesystem.model.User;
import savethesystem.dao.SessionDAO;
import savethesystem.ui.LeaderboardFrame;

/**
 *
 * @author LENOVO
 */
public class GameOverFrame extends javax.swing.JFrame {
    private int sessionId;
    private User currentUser;
    

    /**
     * Creates new form GameOverFrame
     */
    public GameOverFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }
    public GameOverFrame(User user, int sessionId, int finalScore) {
    initComponents();
    setLocationRelativeTo(null);

    this.currentUser = user;
    this.sessionId = sessionId;

    lblFinalScore.setText("Your Score: " + finalScore);
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblFinalScore = new javax.swing.JLabel();
        btnPlayAgain = new javax.swing.JButton();
        btnBackToLogin = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        btnViewLeaderboard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Papyrus", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("GAME OVER");

        lblFinalScore.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        lblFinalScore.setForeground(new java.awt.Color(204, 51, 0));
        lblFinalScore.setText("Your Score: 0");

        btnPlayAgain.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        btnPlayAgain.setForeground(new java.awt.Color(0, 51, 153));
        btnPlayAgain.setText("Play Again");
        btnPlayAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayAgainActionPerformed(evt);
            }
        });

        btnBackToLogin.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        btnBackToLogin.setForeground(new java.awt.Color(153, 0, 51));
        btnBackToLogin.setText("Back to Login");
        btnBackToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToLoginActionPerformed(evt);
            }
        });

        lblMessage.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        lblMessage.setText("Nice try! Improve your score!");

        btnViewLeaderboard.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        btnViewLeaderboard.setForeground(new java.awt.Color(102, 102, 102));
        btnViewLeaderboard.setText("View Leaderboard");
        btnViewLeaderboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLeaderboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(lblFinalScore))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(lblMessage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(btnPlayAgain))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(btnBackToLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(btnViewLeaderboard)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblMessage)
                .addGap(45, 45, 45)
                .addComponent(lblFinalScore)
                .addGap(64, 64, 64)
                .addComponent(btnViewLeaderboard)
                .addGap(31, 31, 31)
                .addComponent(btnPlayAgain)
                .addGap(32, 32, 32)
                .addComponent(btnBackToLogin)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayAgainActionPerformed
        // TODO add your handling code here:
        SessionDAO sessionDAO = new SessionDAO();
        sessionDAO.finishSession(sessionId); // tutup session lama dulu
        
        GameFrame gf = new GameFrame(currentUser); // session baru akan dibuat otomatis
        gf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPlayAgainActionPerformed

    private void btnBackToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToLoginActionPerformed
        // TODO add your handling code here:
    int confirm = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Yakin mau kembali ke Login?",
        "Konfirmasi",
        javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        SessionDAO sessionDAO = new SessionDAO();
        sessionDAO.finishSession(sessionId);

        LoginFrame lf = new LoginFrame();
        lf.setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_btnBackToLoginActionPerformed

    private void btnViewLeaderboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLeaderboardActionPerformed
        // TODO add your handling code here:
        LeaderboardFrame lb = new LeaderboardFrame(this);
        lb.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_btnViewLeaderboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameOverFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameOverFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameOverFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameOverFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameOverFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToLogin;
    private javax.swing.JButton btnPlayAgain;
    private javax.swing.JButton btnViewLeaderboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFinalScore;
    private javax.swing.JLabel lblMessage;
    // End of variables declaration//GEN-END:variables
}
