/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package savethesystem.ui;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import savethesystem.dao.ScoreDAO;
import savethesystem.model.Score;
import savethesystem.ui.GameOverFrame;
import java.awt.Color;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.Component;
import javax.swing.JTable;
/**
 *
 * @author LENOVO
 */
public class LeaderboardFrame extends javax.swing.JFrame {
    private GameOverFrame parent;
    

    /**
     * Creates new form LeaderboardFrame
     */
    public LeaderboardFrame() {
        initComponents();
        applyTheme(); // <-- tambahin ini
        tblLeaderboard.setDefaultEditor(Object.class, null);
        setLocationRelativeTo(null);
        this.parent = null;
        loadLeaderboard();

        tblLeaderboard.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblLeaderboard.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblLeaderboard.getColumnModel().getColumn(2).setPreferredWidth(100);
    }   
        
    
    public LeaderboardFrame(GameOverFrame parent) {
    initComponents();
    applyTheme(); // <-- tambahin ini
        tblLeaderboard.setDefaultEditor(Object.class, null);
        setLocationRelativeTo(null);

        this.parent = parent;
        loadLeaderboard();

        tblLeaderboard.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblLeaderboard.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblLeaderboard.getColumnModel().getColumn(2).setPreferredWidth(100);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLeaderboard = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Leaderboard");

        tblLeaderboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rank", "Username", "Score", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLeaderboard);

        btnBack.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(315, 315, 315))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBack)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(125, 125, 125))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addGap(71, 71, 71)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnBack)
                .addContainerGap(263, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        if (parent != null) {
            parent.setVisible(true);   // balik ke GameOverFrame
        }
        this.dispose();  // tutup leaderboard
    }//GEN-LAST:event_btnBackActionPerformed

    private void loadLeaderboard() {
    DefaultTableModel model = (DefaultTableModel) tblLeaderboard.getModel();
    model.setRowCount(0);

    ScoreDAO dao = new ScoreDAO();
    List<Score> list = dao.getBestScoresPerUser(10);

    int rank = 1;
    for (Score s : list) {
        model.addRow(new Object[]{rank, s.getUsername(), s.getFinalScore(), s.getResult()});
        rank++;
    }
}
    private void applyTheme() {
    // === Opsi C: Soft Blue ===
    Color bg       = new Color(240, 248, 255); // #F0F8FF (AliceBlue)
    Color title    = new Color(30, 58, 138);   // #1E3A8A (judul)
    Color headerBg = new Color(179, 217, 255); // #B3D9FF (header tabel)
    Color accent   = new Color(37, 99, 235);   // #2563EB (tombol)
    Color grid     = new Color(153, 204, 255); // mirip yang kamu pakai

    // Background utama frame
    getContentPane().setBackground(bg);
    jScrollPane1.getViewport().setBackground(bg);
    // Judul
    jLabel1.setForeground(title);

    // Tombol
    btnBack.setBackground(accent);
    btnBack.setForeground(Color.WHITE);
    btnBack.setFocusPainted(false);
    
    DefaultTableCellRenderer center = new DefaultTableCellRenderer();
    center.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    tblLeaderboard.getColumnModel().getColumn(0).setCellRenderer(center); // Rank
    tblLeaderboard.getColumnModel().getColumn(2).setCellRenderer(center); // Score
    tblLeaderboard.getColumnModel().getColumn(3).setCellRenderer(center); // Result

    // JTable + header
    tblLeaderboard.setBackground(Color.WHITE);
    tblLeaderboard.setForeground(Color.BLACK);
    tblLeaderboard.setGridColor(grid);
    tblLeaderboard.setRowHeight(28); // biar enak dilihat (boleh ubah)

    tblLeaderboard.getTableHeader().setBackground(headerBg);
    tblLeaderboard.getTableHeader().setForeground(title);
    tblLeaderboard.getTableHeader().setReorderingAllowed(false);

    // Baris selang-seling (zebra) biar rapi
    tblLeaderboard.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(
                JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

            if (!isSelected) {
                c.setBackground((row % 2 == 0) ? new Color(250, 252, 255) : Color.WHITE);
                c.setForeground(Color.BLACK);
            } else {
                c.setBackground(new Color(219, 234, 254)); // warna seleksi soft
                c.setForeground(Color.BLACK);
            }
            return c;
        }
    });
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeaderboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeaderboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeaderboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeaderboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeaderboardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLeaderboard;
    // End of variables declaration//GEN-END:variables
}
