/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package savethesystem.ui;
import savethesystem.model.User;
import savethesystem.dao.SessionDAO;
import savethesystem.ui.LeaderboardFrame;
import javax.swing.ImageIcon;
import java.awt.Color;
import java.awt.Font;
/**
 *
 * @author LENOVO
 */
public class YouWinFrame extends javax.swing.JFrame {
    private int sessionId;
    private User currentUser;
    private int finalScore;
    

    /**
     * Creates new form YouWinFrame
     */
    public YouWinFrame() {
        float[] dist = {0.0f, 0.6f, 1.0f};
        Color[] colors = {
            new Color(120, 90, 10),    // emas gelap atas
            new Color(245, 215, 110),  // soft gold tengah
            new Color(255, 240, 180)   // highlight bawah
    };
        
    setContentPane(new GradientPanel(dist, colors));
    initComponents();       
    setLocationRelativeTo(null);
    
    makeTransparent(getContentPane());
    fixButtons();
    
    }
 
    public YouWinFrame(User user, int sessionId, int finalScore) {
    float[] dist = {0.0f, 0.6f, 1.0f};
        Color[] colors = {
            new Color(120, 90, 10),    // emas gelap atas
            new Color(245, 215, 110),  // soft gold tengah
            new Color(255, 240, 180)   // highlight bawah
        };
    setContentPane(new GradientPanel(dist, colors));
    initComponents(); 
    setLocationRelativeTo(null);

        this.currentUser = user;
        this.sessionId = sessionId;
        this.finalScore = finalScore;

        lblFinalScore.setText("Final Score: " + finalScore);

        // ✅ Styling Title (YOU WIN!)
        jLabel1.setFont(new Font("Arial Black", Font.BOLD, 48));
        jLabel1.setForeground(new Color(0, 255, 0)); // hijau
        jLabel1.setText("YOU WIN!");

        // ✅ Trophy Icon (pastikan path benar)
        java.net.URL imgURL = getClass().getResource("/savethesystem/assets/images-removebg-preview.png");

        if (imgURL != null) {
            lblTrophy.setIcon(new ImageIcon(imgURL));
        } else {
            lblTrophy.setText("");
            System.out.println("Trophy icon not found!");
        }
        makeTransparent(getContentPane());
        fixButtons();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBackToLogin = new javax.swing.JButton();
        lblFinalScore = new javax.swing.JLabel();
        btnViewLeaderboard = new javax.swing.JButton();
        btnPlayAgain = new javax.swing.JButton();
        lblTrophy = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("YOU WIN !");

        jLabel2.setFont(new java.awt.Font("SimSun-ExtG", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 0));
        jLabel2.setText("Congratulations! You saved the system.");

        btnBackToLogin.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        btnBackToLogin.setForeground(new java.awt.Color(153, 0, 0));
        btnBackToLogin.setText("Back to Login");
        btnBackToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToLoginActionPerformed(evt);
            }
        });

        lblFinalScore.setFont(new java.awt.Font("MingLiU_MSCS-ExtB", 1, 24)); // NOI18N
        lblFinalScore.setForeground(new java.awt.Color(51, 51, 51));
        lblFinalScore.setText("Final Score: ");

        btnViewLeaderboard.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        btnViewLeaderboard.setForeground(new java.awt.Color(0, 102, 102));
        btnViewLeaderboard.setText("View Leaderboard");
        btnViewLeaderboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLeaderboardActionPerformed(evt);
            }
        });

        btnPlayAgain.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        btnPlayAgain.setForeground(new java.awt.Color(0, 0, 153));
        btnPlayAgain.setText("Play Again");
        btnPlayAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayAgainActionPerformed(evt);
            }
        });

        lblTrophy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/savethesystem/assets/images-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 196, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(190, 190, 190))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewLeaderboard)
                            .addComponent(btnPlayAgain)
                            .addComponent(btnBackToLogin)
                            .addComponent(lblFinalScore)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(lblTrophy))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBackToLogin, btnPlayAgain, btnViewLeaderboard});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(lblTrophy)
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(59, 59, 59)
                .addComponent(lblFinalScore)
                .addGap(35, 35, 35)
                .addComponent(btnViewLeaderboard)
                .addGap(35, 35, 35)
                .addComponent(btnPlayAgain)
                .addGap(39, 39, 39)
                .addComponent(btnBackToLogin)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBackToLogin, btnPlayAgain, btnViewLeaderboard});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayAgainActionPerformed
        // TODO add your handling code here: 
        SessionDAO dao = new SessionDAO();
        dao.finishSession(sessionId); // tutup session menang

        GameFrame gf = new GameFrame(currentUser); 
        gf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPlayAgainActionPerformed

    private void btnBackToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToLoginActionPerformed
        // TODO add your handling code here:
        SessionDAO dao = new SessionDAO();
        dao.finishSession(sessionId);

        LoginFrame lf = new LoginFrame();
        lf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackToLoginActionPerformed

    private void btnViewLeaderboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLeaderboardActionPerformed
        // TODO add your handling code here:
        LeaderboardFrame lb = new LeaderboardFrame();
        lb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnViewLeaderboardActionPerformed

    private void makeTransparent(java.awt.Container c) {
    for (java.awt.Component comp : c.getComponents()) {
        if (comp instanceof javax.swing.JComponent) {
            ((javax.swing.JComponent) comp).setOpaque(false);
        }
        if (comp instanceof java.awt.Container) {
            makeTransparent((java.awt.Container) comp);
        }
    }
}
    private void fixButtons() {
    // tombol jangan transparan total
    btnPlayAgain.setOpaque(true);
    btnViewLeaderboard.setOpaque(true);
    btnBackToLogin.setOpaque(true);

    btnPlayAgain.setContentAreaFilled(true);
    btnViewLeaderboard.setContentAreaFilled(true);
    btnBackToLogin.setContentAreaFilled(true);

    // biar kontras di background emas
    btnPlayAgain.setBackground(new Color(15, 42, 95));      // navy
    btnPlayAgain.setForeground(Color.WHITE);

    btnViewLeaderboard.setBackground(new Color(37, 99, 235)); // blue
    btnViewLeaderboard.setForeground(Color.WHITE);

    btnBackToLogin.setBackground(new Color(120, 0, 0));     // maroon
    btnBackToLogin.setForeground(Color.WHITE);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YouWinFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YouWinFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YouWinFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YouWinFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YouWinFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToLogin;
    private javax.swing.JButton btnPlayAgain;
    private javax.swing.JButton btnViewLeaderboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblFinalScore;
    private javax.swing.JLabel lblTrophy;
    // End of variables declaration//GEN-END:variables
}
